### ISSUE TITLE
About File deletion

### ISSUE THREAD

**Issue by telegrambotdev** [BassThatHertz/AudioAndVideoConverter#16]
So what about if a user converted 20mb video,and he was going to download that file.

Then suddenly another user added 4gb video for convertion.as per your concept,the convertion folder must be emptied before every convertion.so the 1st user cant download the video,if another user started a convertion.right ?

**Comment by telegrambotdev** [comment]
The better idea is implement a feature like autodelete the uploaded and converted  files after `"X" hours`,based on the uploaded time.

else please add a file size limit for convertions folder too(like 3gb limit,which you did to the uploads folder) ,then i can set a high value to prevent sudden deletions.better idea is the First one.

**Comment by BassThatHertz** [comment]
> The better idea is implement a feature like autodelete the uploaded and converted files after "X" hours,based on the uploaded time.

I'm not sure how to do this, unless I have an infinite `while True` loop that keeps looking at the current time and deletes the file after X hours. But an infinite `while` loop would be blocking, meaning the the rest of the code wouldn't execute.

If you have an idea on how to implement the autodelete feature after X hours without it hindering other aspects of this web app, you are free to play around with the code and issue a pull request if you come up with a good solution. 

By the way, do you have a platform where we can message each other and discuss improvements to this web application? Perhaps Telegram or preferably Discord (due to being able to easily share formatted code). I'm **BassThatHertz#4416** on Discord.

**Comment by telegrambotdev** [comment]
i am not using discord.
can you ping me on telegram `@animal_de_compagnie`

**Comment by BassThatHertz** [comment]
The method used to empty folders has been improved. See [this ](https://github.com/BassThatHertz/AudioAndVideoConverter/commit/b8dda00ef1b66a8ca1ce079646c40038fcc2576f)commit.
